development:
  # adapter: postgresql
  # #database: twitter
  # database: hotelbooking
  # username: postgres
  # password: postgres
  # pool: 5
  # timeout: 5000
  # #host: 192.168.9.89
  # host: localhost
  # #port: 5440
  # port: 5432
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: hotelbooking
  username: xuanchien
  password: "123456"
  host: 192.168.10.40
  port: 3306
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: hotelbooking
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: hotelbooking
  username: xuanchien
  password: "123456"
  host: 192.168.10.40
  port: 3306
