class AddIndexesToLocalDatabase < ActiveRecord::Migration
  def change
    # add_index 'hotel_image_lists', 'EANHotelID'
    # add_index 'chain_lists', 'ChainCodeID'
    # add_index 'property_description_lists', 'EANHotelID'
    # add_index 'recreation_description_lists', 'EANHotelID'
    # add_index 'policy_description_lists', 'EANHotelID'
    # add_index 'area_attraction_lists', 'EANHotelID'
    # add_index 'what_to_expect_lists', 'EANHotelID'
    # add_index 'spa_description_lists', 'EANHotelID'
    # add_index 'dining_descriptions_lists', 'EANHotelID'
    # add_index 'room_type_lists', 'EANHotelID'
    # add_index 'room_type_lists', 'RoomTypeID'
    # add_index 'attribute_lists', 'AttributeID'
    # add_index 'property_attribute_links', 'EANHotelID'
    # add_index 'property_attribute_links', 'AttributeID'
    # add_index 'gds_attribute_lists', 'AttributeID'
    # add_index 'gds_property_attribute_links', 'EANHotelID'
    # add_index 'gds_property_attribute_links', 'AttributeID'
    # add_index 'property_amenities', 'PropertyAmenityID'
    # add_index 'property_amenities', 'PropertyID'
    # add_index 'hotel_descriptions', 'HotelID'
    # add_index 'star_ratings', 'HotelID'
    # add_index 'landmark_destinations', 'DestinationID'
    # add_index 'property_room_types', 'PropertyID'
    # add_index 'destination_ids', 'DestinationID'
    # add_index 'currencies', 'CurrencyCode'
    # add_index 'property_theme_data', 'PropertyID'
  end
end
